deployment:
  tasks:
    - export APP_NAME="dml-lms"
    - export RELEASE="$HOME/apps/$APP_NAME/current"
    - export SHARED="$HOME/apps/$APP_NAME/shared"
    - export SUBDOMAIN_DOCROOT="$HOME/public_html/stagging-lms.ahdirmai.id"

    - /bin/mkdir -p "$RELEASE" "$SHARED/storage"

    - /usr/bin/rsync -a --delete \
        --exclude ".git" \
        --exclude ".cpanel.yml" \
        --exclude "node_modules" \
        --exclude "vendor" \
        --exclude "storage" \
        ./ "$RELEASE/"

    - /bin/ln -snf "$SHARED/.env" "$RELEASE/.env"
    - /bin/rm -rf "$RELEASE/storage" && /bin/ln -snf "$SHARED/storage" "$RELEASE/storage"

    - if [ -x /opt/cpanel/composer/bin/composer ]; then COMPOSER="/opt/cpanel/composer/bin/composer"; else COMPOSER="$(command -v composer)"; fi
    - /usr/local/bin/php -d memory_limit=-1 "$COMPOSER" -d "$RELEASE" install --no-dev --prefer-dist --no-interaction --optimize-autoloader

    - if ! /usr/local/bin/php -r "echo (int) (strlen(@parse_ini_file('$RELEASE/.env')['APP_KEY']??''));" | grep -q '[1-9]'; then /usr/local/bin/php "$RELEASE/artisan" key:generate --force; fi

    - if [ -d "$SUBDOMAIN_DOCROOT" ] && [ ! -L "$SUBDOMAIN_DOCROOT" ]; then mv "$SUBDOMAIN_DOCROOT" "${SUBDOMAIN_DOCROOT}.bak-$(date +%s)"; fi
    - /bin/ln -snf "$RELEASE/public" "$SUBDOMAIN_DOCROOT"

    - /usr/local/bin/php "$RELEASE/artisan" storage:link || true
    - /usr/local/bin/php "$RELEASE/artisan" migrate --force || true
    - /usr/local/bin/php "$RELEASE/artisan" optimize

    - /bin/echo "✅ Deploy MINIMAL+ selesai @ $(date -u +%Y-%m-%dT%H:%M:%SZ)"
