---
deployment:
  tasks:
    # 1️⃣ Masuk ke direktori project
    - cd /home/ahdirmai/repositories/app/dev-dml-lms

    # 2️⃣ Jalankan composer install untuk update dependency
    - /opt/cpanel/composer/bin/composer install --no-interaction --prefer-dist --optimize-autoloader

    # 3️⃣ Jalankan migrasi database (jika ada perubahan schema)
    - /usr/local/bin/php artisan migrate --force

    # 4️⃣ Bersihkan dan rebuild cache konfigurasi, route, dan view
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:clear
    - /usr/local/bin/php artisan view:cache

    # 5️⃣ Set permission folder penting agar bisa di-write
    - chmod -R 775 storage bootstrap/cache
    - chown -R $USER:$USER storage bootstrap/cache

    # 6️⃣ Generate APP_KEY jika belum ada
    - if [ ! -s .env ]; then echo "APP_KEY belum ada, membuat..." && /usr/local/bin/php artisan key:generate --force; fi
